### ISSUE TITLE
workplan for migrating the metrics config UI to utilize APIs / svelte-query

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1216]
We'll be migrating both modeling and metrics over to the new editing paradigm. Sources will also need some work from platform.

See [this notion doc](https://www.notion.so/rilldata/Frontend-state-management-e3d93497db8e4fd08508755e4fc21eaf) for more information.

## General
- [ ] renaming artifact / frontend: renaming an artifact should redirect to a new route w/ the new artifact name
- [ ] renaming artifact / runtime: create endpoint to simplify this (rename artifact endpoint, then call `migrate` with old and new name of path, possibly `moveAndMigrate(old, new)`)
- [ ] deleting artifact / runtime: create endpoint to simplify this

## Sources

see https://github.com/rilldata/rill-developer/pull/1227 for a more thorough breakdown

- [ ] sources / frontend: compile to YAML rather than SQL
- [ ] utilize `putAndMigrate` endpoint rather than `migrateDirect`
- [ ] integrate errors (if needed)
- [ ] move from uuid -> name

## Models
- [ ] editing flow needs to go through the runtime APIs `putAndMigrate` (keystroke-by-keystroke. `put` will prepopulate the hint for performance reasons)
- [ ] cut out editing-specific pieces from the Node APIs
- [ ] query queue: renaming a model should clear the query queue for the existing model name / key
- [ ] move from uuid -> name

## Metrics
- [ ] replace redux thunks with the one API call
- [ ] add an `addMetricsDefinition` hack that targets existing node api to keep dashboard working. If dashboard changes land beforehand, we can throw this out.
- validation will only have duckdb validation, not the full SQL parsing validation utilizing the Nearley parser (file an issue for this)
- [ ] move from uuid -> name

## Dashboard
- [ ] update id to filename
- [ ] call runtime host instead of nodejs host

Open questions:
- validation – ideally it lives in the runtime, but comparable validation requires the runtime to be aware of a model's columns. There may be an easy solution; if not, we can migrate the parsing of the expression to the frontend. It will require us to check on how our nearley parse works in the browser (most likely it will work fine)
