### ISSUE TITLE
Runtime & application migration burndown

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1231]
## Analytical APIs
- [ ] Use cardinality of sources to show rows diff (@hamilton)
- [ ] Remove buttons from numeric queries if there's no data (@hamilton)
- [ ] Move to new API for column widths

## CLI

- [ ] **OPTIONAL** ability to re-hydrate project w/o starting application

## Dashboard artifacts
- [ ] Comments and YAML keys should be cleaned up #1383 

## Telemetry
- [ ] **NEEDS DE-RISKING, PUNT TO 17** – in telemetry, we're hashing the last part of the project folder as the project id. hash project name, hash install id. More thinking is needed here. We can look at the first commit hash as a stable identifier for a project, and possibly also look at a hashed version of the origin to see about number of forks.

## Debugging
- [ ] **BLOCKER** Duplicate column names break UI (@hamilton)
- [ ] Empty rows from models – handle case where no rows are returned in preview table
- [ ] Renaming model doesn't propagate error to dashboard. @AdityaHegde 
- [ ] Humanize is buggy #1359
- [ ] Add back disabling telemetry for CI in go @AdityaHegde #1364
- [ ] **OPTIONAL** – Global duckdb query status for the spinner
- [ ] Simplify RootConfig and replace global config with constants perhaps? – @AdityaHegde 
- [ ] Deleting and adding back a dashboard doesnt render leaderboard and timeseries.
- [ ] Editing a model query does not trigger some of the column profile queries to rerun

Last...
- [ ] update dev commands in readme
- [ ] Delete all Node code from backend and package.json
- [ ] Add a top-level Reconcile (but understand the UX consequences)
- [ ] Test everything!

**Comment by hamilton** [comment]
Closing this issue in favor of the burndown list we're tracking in notion.
