### ISSUE TITLE
[meta] minimum-viable navigation changes

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1620]
This meta issue will track a few changes for v20 re: the navigation:

### P0s
- [ ] #1621
- [x] #1622
- [ ] #1623
- [x] change button styling to accommodate a wider variety of spaces

### P1s
- [ ] navigation: if no dashboard, change the CTA of the `dashboards` section
- [ ] models: if no model, change the CTA of the `models` section

**Comment by hamilton** [comment]
We're de-prioritizing this work; closing this isssue for now.
