### ISSUE TITLE
add an MVP metrics definition UI & state

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#213]
**Initiative**
Create a [proposal](https://www.notion.so/rilldata/Metrics-Config-UI-93ebae5e845c4dcea1023d82a653b0e7) with [mocks](https://www.figma.com/file/sJ6lGZTHIWwzS5kdKF9Z0c/Metrics-Explorer-Tech-Preview?node-id=0%3A1) for a metrics config form UI. Will align with [Metrics API](https://www.notion.so/rilldata/Rill-backend-design-86084c1eb1f24704aeb5cf49cd29719e) work down the road. Break this work out into actionable tasks. Should support the following features:

Parameters: dimensions, measurements
Metadata: descriptions, titles, formatting rules
Time series: time series parameter, time granularity (might not need this, can estimate min time grain)

Scope of this epic includes (1) the metrics config state, (2) the UI implementation, and (3) the integration into navigation.

**Checklist of Issues**

- [ ]

**Comment by hamilton** [comment]
looks like this still needs to be broken out. @bcolloran can you get this together by early next week?

**Comment by magorlick** [comment]
@bcolloran to break this out into issues by Wednesday of this week.

**Comment by bcolloran** [comment]
**updates to existing components**
- [ ] add section to side nav for metrics definitions
- [ ] allow hiding of right pane when in metrics definition task

**state management**
- [ ] add inititial redux store support to app
- [ ] add Metrics Definition UI state to app
- [ ] enable de/serialization of redux store to/from disk (handled via state service)

**components**
- [ ] [METRICS DEF] dropdown selector component 
- [ ] [METRICS DEF] editable table component
- [ ] [METRICS DEF] editable row component
- [ ] validation icon component
- [ ] summary sparklines component

**Comment by bcolloran** [comment]
closing in favor of https://github.com/rilldata/rill-developer/issues/358
