### ISSUE TITLE
[meta] Metrics Explorer Tech Preview Burndown

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#463]
**Initiative**
A clear and concise description of the problem statement.

_Description_
Build the Metrics Explorer view.

_Problem Statment_
Growing Audience for TAM Expansion Discovery

_Definition of Done_
Ability to tap into prospect and developer communities to begin validating our ideas.

**Resources**
[Notion epic doc link.
](https://www.notion.so/rilldata/Metrics-Explorer-Tech-Preview-73ce7265d859457fa6492af50875f2bd)

**Checklist of Issues**

State
- [x] https://github.com/rilldata/rill-developer/issues/502
- [x] https://github.com/rilldata/rill-developer/issues/501

Leaderboard
- [x] https://github.com/rilldata/rill-developer/issues/314
- [x] https://github.com/rilldata/rill-developer/issues/218
- [x] https://github.com/rilldata/rill-developer/issues/221
- [x] https://github.com/rilldata/rill-developer/issues/468

Menus & Selectors
- [ ] https://github.com/rilldata/rill-developer/issues/308 ** could have help, not ready
- [x] https://github.com/rilldata/rill-developer/issues/309 ** could have help, ready for help, needs design
- [ ] https://github.com/rilldata/rill-developer/issues/310 ** could have help, ready for help, needs design

Pills 
- [ ] https://github.com/rilldata/rill-developer/issues/313** could have help with guidance, ready for help

Line Charts
- [x] https://github.com/rilldata/rill-developer/issues/460
- [x] https://github.com/rilldata/rill-developer/issues/314
- [ ] https://github.com/rilldata/rill-developer/issues/461

Formatting & Polish
- [x] https://github.com/rilldata/rill-developer/issues/307
- [x] https://github.com/rilldata/rill-developer/issues/465
- [x] https://github.com/rilldata/rill-developer/issues/462
- [x] https://github.com/rilldata/rill-developer/issues/464
- [x] https://github.com/rilldata/rill-developer/issues/469
- [x] https://github.com/rilldata/rill-developer/issues/522
- [x] https://github.com/rilldata/rill-developer/issues/523
- [x] https://github.com/rilldata/rill-developer/issues/526
- [x] https://github.com/rilldata/rill-developer/issues/531

API
- [x] https://github.com/rilldata/rill-developer/issues/478

Onboarding
- [x] https://github.com/rilldata/rill-developer/issues/481

**Comment by bcolloran** [comment]
@magorlick @hamilton i'm going to close this as stale, but of course feel free to reopen if this issue is still needed
