### ISSUE TITLE
[meta] Standardize telemetry across to the application

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#805]
**Initiative**
Standardize telemetry across to the application to cover active and behavioral events.

**Resources**
[Notion epic doc link](https://www.notion.so/rilldata/Growth-Metrics-Q3-85e44bd860b6448da2e831a872bca9ce#6630f78e79ba4b688e80f38c086d152c)

**Checklist of Issues**
- [x] Change app name from 'data-modeler' to 'rill-developer' in standard fields.  
- [x] remove IP, city and country info if present anywhere
- [x] Remove `entity_id` and `entity_type` from active event
- [x] #763 
- [x] #818
- [x] #835
